---
- name: Create path for excalidraw app
  ansible.builtin.file:
    path: "{{ excalidraw_config.app_data_path }}"
    state: directory
    owner: root
    group: "{{ app_group }}"
    mode: '0770'

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ excalidraw_config.app_data_path }}/docker-compose.yml"
    owner: root
    group: "{{ app_group }}"
    mode: '0774'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd {{ excalidraw_config.app_data_path }}
    docker compose down
  register: excalidraw_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd {{ excalidraw_config.app_data_path }}
    docker compose up -d
  register: excalidraw_compose_up
  changed_when: true
