---
- name: Create path for wiki app
  ansible.builtin.file:
    path: "{{ planka_config.app_data_path }}"
    state: directory
    owner: root
    group: "{{ app_group }}"
    mode: '0770'

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ planka_config.app_data_path }}/docker-compose.yml"
    owner: root
    group: "{{ app_group }}"
    mode: '0774'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd {{ planka_config.app_data_path }}
    docker compose down
  register: wiki_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd {{ planka_config.app_data_path }}
    docker compose up -d
  register: wiki_compose_up
  changed_when: true
