homer_app_data_path: "{{ app_data_path }}/homer"
homer_image: b4bz/homer
homer_image_version: latest
homer_homer: "{{ traefik_web_vault[0] }}"

homer_proxmox_user: "{{ proxmox_user_vault }}"
homer_proxmox_token_id: "{{ proxmox_token_id_vault }}"
homer_proxmox_token_secret: "{{ proxmox_token_secret_vault }}"
homer_proxmox_node_name: "{{ proxmox_node_name_vault }}"

homer_config:
  title: DASHBOARD
  subtitle: HixLABS
