---
- name: Configure neutron-20
  become: true
  hosts:
    - neutron
  pre_tasks:
    - name: Create group app_data
      ansible.builtin.group:
        name: app_data
        state: present
        # gid: 2000  # Uncomment and specify GID if needed

    - name: Create path /app/data
      ansible.builtin.file:
        path: "/app/data/"
        state: directory
        owner: root
        group: app_data
        mode: '0770'

  roles:
    - role: docker
      tags:
        - docker
    - role: traefik
      tags:
        - traefik
    - role: portainer_agent
      tags:
        - portainer-agent
    - role: homer
      tags:
        - homer
    - role: excalidraw
      tags:
        - excalidraw
    - role: postgres
      tags:
        - postgres
    - role: planka
      tags:
        - planka
