---
- name: Create path for postgres
  ansible.builtin.file:
    path: "{{ postgres_config.app_data_path }}"
    state: directory
    owner: root
    group: "{{ app_group }}"
    mode: '0770'

- name: Create pgdata directory
  ansible.builtin.file:
    path: "{{ postgres_config.app_data_path }}/pgdata"
    state: directory
    owner: root
    group: "{{ app_group }}"
    mode: '0770'

- name: Copy init-multiple-dbs.sh file
  ansible.builtin.template:
    src: init-multiple-dbs.sh.j2
    dest: "{{ postgres_config.app_data_path }}/init-multiple-dbs.sh"
    owner: root
    group: "{{ app_group }}"
    mode: '0774'

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ postgres_config.app_data_path }}/docker-compose.yml"
    owner: root
    group: "{{ app_group }}"
    mode: '0774'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd {{ postgres_config.app_data_path }}
    docker compose down
  register: posgresql_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd {{ postgres_config.app_data_path }}
    docker compose up -d
  register: posgresql_compose_up
  changed_when: true
