---
- name: Create path for homer app
  ansible.builtin.file:
    path: "{{ homer_app_data_path }}"
    state: directory
    owner: root
    group: "{{ app_group }}"
    mode: '0770'

- name: Create assets directory
  ansible.builtin.file:
    path: "{{ homer_app_data_path }}/assets"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Copy all assets files
  ansible.builtin.copy:
    src: assets/
    dest: "{{ homer_app_data_path }}/assets/"
    owner: 1000
    group: 1000
    mode: '0755'

- name: Copy config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ homer_app_data_path }}/assets/config.yml"
    owner: 1000
    group: 1000
    mode: '0755'

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homer_app_data_path }}/docker-compose.yml"
    owner: root
    group: "{{ app_group }}"
    mode: '0774'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd {{ homer_app_data_path }}
    docker compose down
  register: homer_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd {{ homer_app_data_path }}
    docker compose up -d
  register: homer_compose_up
  changed_when: true
